### ISSUE TITLE
Add maintainers and transfer ownership

### ISSUE THREAD

**Issue by posborne** [alexcrichton/mio-uds#25]
`mio-uds` continues to be used (I think correctly) as part of the crate graph for tokio-net but is currently lacking active maintainership (see https://github.com/alexcrichton/mio-uds/pull/23#issuecomment-520871463).  I am actively actively making use of the crate (via tokio) and would be willing to take over as a maintainer for this code.

I think an argument could be made for moving the repo to the tokio-rs org which would give team members in that org the commit bit as well.

CC @carllerche @alexcrichton

**Comment by carllerche** [comment]
UDS is being included in `mio` itself: https://github.com/tokio-rs/mio/pull/1098

**Comment by posborne** [comment]
> UDS is being included in mio itself: tokio-rs/mio#1098

Ah, missed that change.

**Comment by papertigers** [comment]
@alexcrichton looks like there’s interest in ownership. Pinging here because I would like the PR you commented on merged since it fixes tokio on illumos. 

Edit:
Looks like I misread this the last time I passed through, sorry about that. It seems mio itself has grown support for uds, but it's not yet in a released version other than the alpha.

**Comment by pfmooney** [comment]
If the tokio/mio folks are willing to move this repository over as a means of transferring maintainership, that seems like it would work.  Otherwise, either @posborne and/or @jclulow and I are interested in stepping up to help with this work.

@alexcrichton What's your preferred course of action?

**Comment by alexcrichton** [comment]
I don't mind transferring this repo and the crate, would someone like to volunteer to take ownership of the repo and crate?

**Comment by pfmooney** [comment]
Folding it under the @tokio-rs org seems like a natural fit, considering it's one of the primary consumers.  Does that seem palatable to the core folks there (ping @carllerche @Thomasdezeeuw)?  @jclulow and I are certainly interested in stepping up to help with maintenance if the added burden is a concern.

**Comment by Thomasdezeeuw** [comment]
@pfmooney are you talking about maintain Mio-uds for Mio v0.6? Because as @carllerche mentioned in v0.7 Mio supports UDS, e.g. see https://docs.rs/mio/0.7.0/mio/net/struct.UnixDatagram.html. I haven't used this crate so I can't say for sure, but I think missing API in Mio v0.7 (w.r.t UDS) can be added easily.

**Comment by Thomasdezeeuw** [comment]
Also cc @kleimkuhler who added support for UDS to Mio.

**Comment by pfmooney** [comment]
> @pfmooney are you talking about maintain Mio-uds for Mio v0.6? Because as @carllerche mentioned in v0.7 Mio supports UDS, e.g. see https://docs.rs/mio/0.7.0/mio/net/struct.UnixDatagram.html. I haven't used this crate so I can't say for sure, but I think missing API in Mio v0.7 (w.r.t UDS) can be added easily.

`mio-uds` is used by Tokio today.  Until Tokio is updated to use `mio` 0.7, with its own UDS support, it would be nice for that functionality to exist via `mio-uds`.  (And once Tokio is updated to 0.7, for the older version to continue working for a time.)

**Comment by Thomasdezeeuw** [comment]
@pfmooney I understand the need to support Tokio, but couldn't we keep Mio-uds as is and say the next version is rolled into Mio? Deprecating (but still supporting) Mio-uds and suggesting Mio's UDS types instead?

**Comment by pfmooney** [comment]
> @pfmooney I understand the need to support Tokio, but couldn't we keep Mio-uds as is and say the next version is rolled into Mio? Deprecating (but still supporting) Mio-uds and suggesting Mio's UDS types instead?

Considering other direct `mio` users beyond Tokio, it would be nice to have `mio-uds` in working order without being forced across that 0.6.x -> 0.7.x boundary.  If you feel the Tokio/mio project doesn't have the bandwidth to do the `mio-uds` maintenance, @jclulow and I are happy to take on the task.

**Comment by Thomasdezeeuw** [comment]
> Considering other direct `mio` users beyond Tokio, it would be nice to have `mio-uds` in working order without being forced across that 0.6.x -> 0.7.x boundary. If you feel the Tokio/mio project doesn't have the bandwidth to do the `mio-uds` maintenance, @jclulow and I are happy to take on the task.

Is Mio-uds currently not working with Mio v0.6? Like I said before it can be deprecated, suggesting people to move to Mio v0.7, while maintaining Mio-uds (for Mio v0.6).

As an aside I personally don't plan on supporting Mio v0.6 very long, preferably the ecosystem moves to v0.7 (which close to a v1 in terms of API) this year. Do note that this is my personal opinion and I'm not the only maintainer of Mio, so others might have different plans.

**Comment by pfmooney** [comment]
> Is Mio-uds currently not working with Mio v0.6? 

`mio-uds` requires minor updates in order to work on illumos.

> Like I said before it can be deprecated, suggesting people to move to Mio v0.7, while maintaining Mio-uds (for Mio v0.6).

Agreed.  That's why @jclulow and I are interested in putting in the work to keep it viable while `mio` v0.6.x remains in common usage.

> As an aside I personally don't plan on supporting Mio v0.6 very long, preferably the ecosystem moves to v0.7 (which close to a v1 in terms of API) this year. Do note that this is my personal opinion and I'm not the only maintainer of Mio, so others might have different plans.

I agree that widespread adoption of the new version would be ideal.  Until the new version reaches the point of ubiquity, it would be nice to to continue the maintenance for 0.6 in order to at least accept minor fixes like these platform-enabling patches, provided they don't seem to risky.

**Comment by pfmooney** [comment]
@alexcrichton If you're interested in handing over maintenance, @jclulow and I are happy to pick it up via the same @deprecrated effort proposed for `net2-rs`.

**Comment by alexcrichton** [comment]
Sure, what do I need to do to help with that?

**Comment by jclulow** [comment]
Looking at [Transferring a repository](https://help.github.com/en/github/administering-a-repository/transferring-a-repository), it seems like:

> * To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

I think if you add either Patrick or myself as an owner on this repository, we could then effect the transfer as we would have rights both here and there.

As for crates.io, I assume you just have to add either of our GitHub accounts as able to publish for the crate and we can then do whatever subsequent ACL change is required.  I haven't done one of those transfers myself yet though, so I do not know exactly which buttons to push.

**Comment by alexcrichton** [comment]
Er I meant where is the repository transferred to and what does the example of net2 look like. I can handle all the details I just need to know exactly what the details are.

**Comment by jclulow** [comment]
Oh, sorry!  Our intent is for `rust-lang-nursery/net2-rs` to move to `deprecrated/net2-rs` under the [deprecrated](https://github.com/deprecrated) GitHub organisation that @pfmooney  and I have set up to house what we expect to be a handful of crates that are deprecated but which could use sustaining maintenance from time to time while people figure out how to move off.  I think we've nearly got all of the approvals at this point for `net2`, as shown in rust-lang-nursery/net2-rs#102.  Once that process completes we'll firm up the description of that deprecated status in the repository README.

For this crate I would expect it to move to `deprecrated/mio-uds` and we would then do basically the same thing: update the README to make clear what the status is, work through any PRs for critical bug fixes or issues like new platform support, make a release, etc.  Folks would be encouraged to move to the newer `mio` that contains the functionality directly, but we'll keep the lights on.

Is that the right sort of detail?  If not, please let me know and I can answer whatever you need!  Thanks for your help so far.

**Comment by alexcrichton** [comment]
Ok sounds good to me! Want me to transfer the repo to you @jclulow then and I'll add you on crates.io? Looks like net2 is a done deal so I can go ahead and do this too.

**Comment by pfmooney** [comment]
> Ok sounds good to me! Want me to transfer the repo to you @jclulow then and I'll add you on crates.io? Looks like net2 is a done deal so I can go ahead and do this too.

I've invited you to @deprecrated where you should have the rights to initiate the transfer.

**Comment by alexcrichton** [comment]
Ok! I've added @pfmooney as an owner on crates.io and transferred the repository.

**Comment by pfmooney** [comment]
> Ok! I've added @pfmooney as an owner on crates.io and transferred the repository.

Much appreciated.  Thanks for your help.
