### ISSUE TITLE
Android compile error: mismatched types

### ISSUE THREAD

**Issue by Txuritan** [alexcrichton/mio-uds#9]
I'm at a loss on this, I've been looking into what could be causing this, both your crate and libc use c_int as the ```bind``` socket parameter.

Although libc has noticted this ([link](https://github.com/rust-lang/libc/blob/master/src/unix/notbsd/android/b64/mod.rs#L159)).

Sorry that I couldn't give you more info than this.

I'm using the latest version that Termux has for aarch64-linux-android (aka the cargo/rustc packages by pointless).

Error:
```
error[E0308]: mismatched types
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.4/src/datagram.rs:33:48
   |
33 |             try!(cvt(libc::bind(fd.fd(), addr, len)));
   |                                                ^^^ expected i32, found u32

error[E0308]: mismatched types
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.4/src/listener.rs:37:48
   |
37 |             try!(cvt(libc::bind(fd.fd(), addr, len)));
   |                                                ^^^ expected i32, found u32

error: aborting due to 2 previous errors

error: Could not compile `mio-uds`.
```

**Comment by alexcrichton** [comment]
Thanks for the report! I'd definitely be down for a PR which added the necessary casts here to get this working.

**Comment by prasannavl** [comment]
Ok, I'm receiving an exact opposite error now, because of this merge.

```
error[E0308]: mismatched types
  --> /home/pvl/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.6/src/datagram.rs:34:48
   |
34 |             try!(cvt(libc::bind(fd.fd(), addr, len as Len)));
   |                                                ^^^^^^^^^^ expected u32, found i32

error[E0308]: mismatched types
  --> /home/pvl/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.6/src/listener.rs:38:48
   |
38 |             try!(cvt(libc::bind(fd.fd(), addr, len as Len)));
   |                                                ^^^^^^^^^^ expected u32, found i32

error: aborting due to 2 previous errors
```

compiling for android.

**Comment by prasannavl** [comment]
Ok, it compiles successfully with `i686-linux-android` and `armv7-linux-androideabi` but fails with the above error when building for `aarch64-linux-android`. 

Looks like the supposed fix introduced some discrepancy, considering it was supposed to be for `aarch64-linux-android`.

@alexcrichton Reopen this?

Ref: https://github.com/alexcrichton/mio-uds/commit/2ec1b9cf43220cab36311db582a9b1804fd50fd5

Note, I should probably mention that I'm cross-compiling from an x64 machine with the latest NDK standalone compilers. 

```
arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)
i686-linux-android-gcc (GCC) 4.9.x 20150123 (prerelease)
aarch64-linux-android-gcc (GCC) 4.9.x 20150123 (prerelease)
```

**Comment by Txuritan** [comment]
So it looks like an update, either in one of the crates or the NDK itself.

Since then I've received an update (through termux) on the NDK, and this crate merging a pull and the issue returned, although now u32 to i32.

@prasannavl It could be the type cast that's happening when passing the variable. A pull request was made that removed most of the changes done here. The casts are the only part remaining.

**Comment by Txuritan** [comment]
I just tested it with the casts removed and it compiled, it seems that they aren't necessarily any more although I have yet to test it anywhere else other than Android.

**Comment by vorner** [comment]
Hello

What is the status about here? Because like @prasannavl I'm getting the „opposite“ error now.

Would using something like `libc::bind(fd.fd(), addr, len as _)` work in both/all versions?

**Comment by Txuritan** [comment]
My pull request #17, should be the fix to this but I've been unable to get Android's NDK to a point at which I could attempt to compile the library.

In theory, it should be fine to merge, I just haven't been able to test it anywhere else yet.

**Comment by ncalexan** [comment]
This is biting us over in https://github.com/mozilla/application-services -- see https://tools.taskcluster.net/groups/G8KKbrVURw2MNQcxceD4AQ/tasks/F7taOdYHQCa7CtaN_oOMpw/runs/0/logs/public%2Flogs%2Flive.log.
